#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
NAME=podman-daemon
PROG=/usr/bin/podman

start_service() {
 mkdir -p /run/podman
 procd_open_instance
 procd_set_param command "$PROG" system service -t 0
 procd_set_param respawn
 procd_set_param file /run/podman/podman.sock
 procd_set_param stdout 1
 procd_set_param stderr 1
 procd_close_instance
}

stop_service() {
 killall podman 2>/dev/null
}
