name: Release

on:
  workflow_run:
    workflows: ["ImmortalWrt"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-24.04
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: 检出代码
      uses: actions/checkout@v6

    - name: 环境准备
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        mkdir -p ${{ github.workspace }}/artifact

        # 安装 jq 用于解析 GitHub API 响应
        sudo -E apt-get -y update
        sudo -E apt-get -y install jq

        # 获取触发本次 workflow 的 ImmortalWrt run id
        echo "IMMORTALWRT_RUN_ID=${{ github.event.workflow_run.id }}" >> $GITHUB_ENV

    - name: 下载固件 ( ImmortalWrt )
      uses: actions/download-artifact@v4
      with:
        name: firmware
        github-token: ${{ secrets.GH_TOKEN }}
        path: ${{ github.workspace }}/artifact
        run-id: ${{ env.IMMORTALWRT_RUN_ID }}

    - name: 检查固件
      run: |
        build_date=$(ls ${{ github.workspace }}/artifact/*.zip | xargs -n 1 basename | awk -F '-' '{print $4}' | sed 's/.zip//' | sort -u)
        [ "${build_date}" == "${build_date/ /_}" ] || exit 1
        echo "BUILD_DATE=$build_date" >> $GITHUB_ENV

    - name: 发布固件
      run: |
        cd ${{ github.workspace }}
        BODY=$(cat ./doc/release.md)
        # 先删除已存在的 release
        gh release delete ${{ env.BUILD_DATE }} --repo x315600/build_openwrt --yes 2>/dev/null || true
        gh release create ${{ env.BUILD_DATE }} \
          --title "${{ env.BUILD_DATE }} 固件发布" \
          --notes "$BODY" \
          artifact/*.zip \
          --repo x315600/build_openwrt
      env:
        GH_TOKEN: *** secrets.GH_TOKEN }}

    - name: TG 通知
      run: |
        message="
        *${{ env.BUILD_DATE }} 固件发布*

        $(awk '/更新内容/{f=1; c=2; next} f && --c<=0' ./doc/release.md | sed 'G')

        [固件下载地址](https://github.com/x315600/build_openwrt/releases/tag/${{ env.BUILD_DATE }}) | [刷机说明](https://github.com/x315600/build_openwrt/doc/readme.md)
        "

        curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_TO }}&text=${message}&parse_mode=MarkDown&disable_web_page_preview=true"
